export const PRICE = [
  { id: 1, name: 'Шаблон', price: 1 },
  { id: 2, name: 'Индивидуальный', price: 2 },
  { id: 3, name: 'Сайты', price: 0 },
  { id: 4, name: 'ТелеграмБот', price: 0 },
  { id: 5, name: 'Приложения', price: 0 },
  { id: 6, name: 'Лендинг', price: 6 },
  { id: 7, name: 'Многостраничный', price: 7 },
  { id: 8, name: 'Магазин', price: 8 },
  { id: 9, name: 'ЧатБот', price: 9 },
  { id: 10, name: 'Магазин Бот', price: 10 },
  { id: 11, name: 'IOS & Andriod', price: 11 },
  { id: 12, name: 'VK App', price: 12 },
  { id: 13, name: 'Иллюстрации', price: 13 },
  { id: 14, name: 'Иконки', price: 14 },
  { id: 15, name: 'Фотографии', price: 15 },
  { id: 16, name: 'Срочно!', price: 16 },
]
